// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	// A client command, handed to the state machine on commit.
	EntryType_ENTRY_TYPE_NORMAL EntryType = 1
	// An empty entry a leader appends to its own log immediately on election.
	// Not decoration: the commit rule forbids committing entries from earlier
	// terms directly, so without an entry of its own term a fresh leader can
	// never advance commitIndex over the backlog it inherited, and read-index
	// reads could never be served.
	EntryType_ENTRY_TYPE_NOOP EntryType = 2
	// A membership change. Carries a marshalled ConfChange in `command`.
	EntryType_ENTRY_TYPE_CONF_CHANGE EntryType = 3
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_NORMAL",
		2: "ENTRY_TYPE_NOOP",
		3: "ENTRY_TYPE_CONF_CHANGE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_NORMAL":      1,
		"ENTRY_TYPE_NOOP":        2,
		"ENTRY_TYPE_CONF_CHANGE": 3,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

type ConfChange_Kind int32

const (
	ConfChange_KIND_UNSPECIFIED ConfChange_Kind = 0
	// Move from C_old to the joint configuration C_old,new.
	ConfChange_KIND_ENTER_JOINT ConfChange_Kind = 1
	// Leave the joint configuration for C_new alone.
	ConfChange_KIND_LEAVE_JOINT ConfChange_Kind = 2
)

// Enum value maps for ConfChange_Kind.
var (
	ConfChange_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ENTER_JOINT",
		2: "KIND_LEAVE_JOINT",
	}
	ConfChange_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_ENTER_JOINT": 1,
		"KIND_LEAVE_JOINT": 2,
	}
)

func (x ConfChange_Kind) Enum() *ConfChange_Kind {
	p := new(ConfChange_Kind)
	*p = x
	return p
}

func (x ConfChange_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfChange_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[1].Descriptor()
}

func (ConfChange_Kind) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[1]
}

func (x ConfChange_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfChange_Kind.Descriptor instead.
func (ConfChange_Kind) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2, 0}
}

// One command in the replicated log. Index and Term together uniquely identify
// an entry across the whole cluster, for all time.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=raft.v1.EntryType" json:"type,omitempty"`
	Command       []byte                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

// The set of nodes that make up the cluster. During a joint-consensus
// membership change, `old_voters` is non-empty and a decision requires a
// majority of BOTH sets — that overlap is what makes it impossible for two
// disjoint majorities to elect two leaders at the same moment.
type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`                        // C_new
	OldVoters     []uint64               `protobuf:"varint,2,rep,packed,name=old_voters,json=oldVoters,proto3" json:"old_voters,omitempty"` // C_old, only during a joint configuration
	Learners      []uint64               `protobuf:"varint,3,rep,packed,name=learners,proto3" json:"learners,omitempty"`                    // replicated to, but never counted in a majority
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *Configuration) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *Configuration) GetOldVoters() []uint64 {
	if x != nil {
		return x.OldVoters
	}
	return nil
}

func (x *Configuration) GetLearners() []uint64 {
	if x != nil {
		return x.Learners
	}
	return nil
}

type ConfChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ConfChange_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=raft.v1.ConfChange_Kind" json:"kind,omitempty"`
	Config        *Configuration         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfChange) Reset() {
	*x = ConfChange{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfChange) ProtoMessage() {}

func (x *ConfChange) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfChange.ProtoReflect.Descriptor instead.
func (*ConfChange) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *ConfChange) GetKind() ConfChange_Kind {
	if x != nil {
		return x.Kind
	}
	return ConfChange_KIND_UNSPECIFIED
}

func (x *ConfChange) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

type Snapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex uint64                 `protobuf:"varint,1,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,2,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	// The configuration in force as of last_included_index. A node that restores
	// from a snapshot has discarded the log entries that established the current
	// membership, so the snapshot has to carry it — otherwise the node comes back
	// not knowing who its peers are.
	Config *Configuration `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// The serialized state machine (the KV map).
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *Snapshot) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *Snapshot) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *Snapshot) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestVoteRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Term         uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId  uint64                 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm  uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	// Pre-vote (Raft thesis §9.6): a straw poll at term+1 that does NOT bump the
	// candidate's own term and does not cause the receiver to bump its term.
	// Without it, a node that was partitioned away returns with an inflated term
	// and forces a healthy leader to step down for no reason.
	PreVote       bool `protobuf:"varint,5,opt,name=pre_vote,json=preVote,proto3" json:"pre_vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() uint64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetPreVote() bool {
	if x != nil {
		return x.PreVote
	}
	return false
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	PreVote       bool                   `protobuf:"varint,3,opt,name=pre_vote,json=preVote,proto3" json:"pre_vote,omitempty"` // echoed, so a late reply can't be misread as a real vote
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *RequestVoteResponse) GetPreVote() bool {
	if x != nil {
		return x.PreVote
	}
	return false
}

// Also serves as the heartbeat, with `entries` empty.
type AppendEntriesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Term         uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId     uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex uint64                 `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint64                 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries      []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit uint64                 `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	// Non-zero when this heartbeat is confirming leadership for a read-index
	// read. Echoed back untouched so the leader can match the quorum of replies
	// to the specific read that triggered them.
	ReadId        uint64 `protobuf:"varint,7,opt,name=read_id,json=readId,proto3" json:"read_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *AppendEntriesRequest) GetReadId() uint64 {
	if x != nil {
		return x.ReadId
	}
	return 0
}

type AppendEntriesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Term    uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// The highest index the follower's log now matches the leader on. Sent
	// explicitly rather than inferred by the leader from what it sent, because a
	// delayed or duplicated response must not be able to move matchIndex
	// backwards or forwards incorrectly.
	MatchIndex uint64 `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	// Not in the paper's Figure 2 — the optimization from §5.3 that lets a leader
	// skip a whole term's worth of entries per round trip instead of backing up
	// one index at a time.
	ConflictIndex uint64 `protobuf:"varint,4,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ConflictTerm  uint64 `protobuf:"varint,5,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	ReadId        uint64 `protobuf:"varint,6,opt,name=read_id,json=readId,proto3" json:"read_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *AppendEntriesResponse) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *AppendEntriesResponse) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *AppendEntriesResponse) GetReadId() uint64 {
	if x != nil {
		return x.ReadId
	}
	return 0
}

// Sent instead of AppendEntries when the follower is so far behind that the
// entries it needs have already been compacted out of the leader's log.
//
// Single-shot: the whole snapshot travels in one message. Chunking (offset/done
// fields and a resumable transfer) is the obvious next step once snapshots get
// large enough for that to matter.
type InstallSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Snapshot      *Snapshot              `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{8}
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotRequest) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type InstallSnapshotResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Term    uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Where the follower's log now starts, so the leader can reset nextIndex.
	MatchIndex    uint64 `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{9}
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallSnapshotResponse) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\araft.v1\"v\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.raft.v1.EntryTypeR\x04type\x12\x18\n" +
	"\acommand\x18\x04 \x01(\fR\acommand\"b\n" +
	"\rConfiguration\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1d\n" +
	"\n" +
	"old_voters\x18\x02 \x03(\x04R\toldVoters\x12\x1a\n" +
	"\blearners\x18\x03 \x03(\x04R\blearners\"\xb4\x01\n" +
	"\n" +
	"ConfChange\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.raft.v1.ConfChange.KindR\x04kind\x12.\n" +
	"\x06config\x18\x02 \x01(\v2\x16.raft.v1.ConfigurationR\x06config\"H\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KIND_ENTER_JOINT\x10\x01\x12\x14\n" +
	"\x10KIND_LEAVE_JOINT\x10\x02\"\xac\x01\n" +
	"\bSnapshot\x12.\n" +
	"\x13last_included_index\x18\x01 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x02 \x01(\x04R\x10lastIncludedTerm\x12.\n" +
	"\x06config\x18\x03 \x01(\v2\x16.raft.v1.ConfigurationR\x06config\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xb0\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x04R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\x12\x19\n" +
	"\bpre_vote\x18\x05 \x01(\bR\apreVote\"g\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\x12\x19\n" +
	"\bpre_vote\x18\x03 \x01(\bR\apreVote\"\xfc\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12+\n" +
	"\aentries\x18\x05 \x03(\v2\x11.raft.v1.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x04R\fleaderCommit\x12\x17\n" +
	"\aread_id\x18\a \x01(\x04R\x06readId\"\xcb\x01\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x04R\n" +
	"matchIndex\x12%\n" +
	"\x0econflict_index\x18\x04 \x01(\x04R\rconflictIndex\x12#\n" +
	"\rconflict_term\x18\x05 \x01(\x04R\fconflictTerm\x12\x17\n" +
	"\aread_id\x18\x06 \x01(\x04R\x06readId\"x\n" +
	"\x16InstallSnapshotRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12-\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x11.raft.v1.SnapshotR\bsnapshot\"h\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x04R\n" +
	"matchIndex*o\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENTRY_TYPE_NORMAL\x10\x01\x12\x13\n" +
	"\x0fENTRY_TYPE_NOOP\x10\x02\x12\x1a\n" +
	"\x16ENTRY_TYPE_CONF_CHANGE\x10\x032\xf6\x01\n" +
	"\x04Raft\x12H\n" +
	"\vRequestVote\x12\x1b.raft.v1.RequestVoteRequest\x1a\x1c.raft.v1.RequestVoteResponse\x12N\n" +
	"\rAppendEntries\x12\x1d.raft.v1.AppendEntriesRequest\x1a\x1e.raft.v1.AppendEntriesResponse\x12T\n" +
	"\x0fInstallSnapshot\x12\x1f.raft.v1.InstallSnapshotRequest\x1a .raft.v1.InstallSnapshotResponseB2Z0github.com/sAchin-680/raftkv/proto/raftpb;raftpbb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_raft_proto_goTypes = []any{
	(EntryType)(0),                  // 0: raft.v1.EntryType
	(ConfChange_Kind)(0),            // 1: raft.v1.ConfChange.Kind
	(*LogEntry)(nil),                // 2: raft.v1.LogEntry
	(*Configuration)(nil),           // 3: raft.v1.Configuration
	(*ConfChange)(nil),              // 4: raft.v1.ConfChange
	(*Snapshot)(nil),                // 5: raft.v1.Snapshot
	(*RequestVoteRequest)(nil),      // 6: raft.v1.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 7: raft.v1.RequestVoteResponse
	(*AppendEntriesRequest)(nil),    // 8: raft.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 9: raft.v1.AppendEntriesResponse
	(*InstallSnapshotRequest)(nil),  // 10: raft.v1.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 11: raft.v1.InstallSnapshotResponse
}
var file_raft_proto_depIdxs = []int32{
	0,  // 0: raft.v1.LogEntry.type:type_name -> raft.v1.EntryType
	1,  // 1: raft.v1.ConfChange.kind:type_name -> raft.v1.ConfChange.Kind
	3,  // 2: raft.v1.ConfChange.config:type_name -> raft.v1.Configuration
	3,  // 3: raft.v1.Snapshot.config:type_name -> raft.v1.Configuration
	2,  // 4: raft.v1.AppendEntriesRequest.entries:type_name -> raft.v1.LogEntry
	5,  // 5: raft.v1.InstallSnapshotRequest.snapshot:type_name -> raft.v1.Snapshot
	6,  // 6: raft.v1.Raft.RequestVote:input_type -> raft.v1.RequestVoteRequest
	8,  // 7: raft.v1.Raft.AppendEntries:input_type -> raft.v1.AppendEntriesRequest
	10, // 8: raft.v1.Raft.InstallSnapshot:input_type -> raft.v1.InstallSnapshotRequest
	7,  // 9: raft.v1.Raft.RequestVote:output_type -> raft.v1.RequestVoteResponse
	9,  // 10: raft.v1.Raft.AppendEntries:output_type -> raft.v1.AppendEntriesResponse
	11, // 11: raft.v1.Raft.InstallSnapshot:output_type -> raft.v1.InstallSnapshotResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		EnumInfos:         file_raft_proto_enumTypes,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
