// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.1
// source: raft.proto

package raftpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Raft_Deliver_FullMethodName = "/raft.v1.Raft/Deliver"
)

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftClient interface {
	// Deliver carries a stream of messages from one peer.
	//
	// Client-streaming rather than unary: a healthy cluster sends heartbeats
	// several times a second to every peer forever, and paying a request/response
	// round trip and its headers for each one is pure overhead. One long-lived
	// stream per peer direction amortizes it away.
	//
	// There is no per-message acknowledgement, deliberately. Raft already assumes
	// an unreliable network and retries on its own schedule; an acknowledgement
	// here would be a second, weaker retry mechanism layered under the real one.
	Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RaftMessage, DeliverAck], error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RaftMessage, DeliverAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Raft_ServiceDesc.Streams[0], Raft_Deliver_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RaftMessage, DeliverAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raft_DeliverClient = grpc.ClientStreamingClient[RaftMessage, DeliverAck]

// RaftServer is the server API for Raft service.
// All implementations must embed UnimplementedRaftServer
// for forward compatibility.
type RaftServer interface {
	// Deliver carries a stream of messages from one peer.
	//
	// Client-streaming rather than unary: a healthy cluster sends heartbeats
	// several times a second to every peer forever, and paying a request/response
	// round trip and its headers for each one is pure overhead. One long-lived
	// stream per peer direction amortizes it away.
	//
	// There is no per-message acknowledgement, deliberately. Raft already assumes
	// an unreliable network and retries on its own schedule; an acknowledgement
	// here would be a second, weaker retry mechanism layered under the real one.
	Deliver(grpc.ClientStreamingServer[RaftMessage, DeliverAck]) error
	mustEmbedUnimplementedRaftServer()
}

// UnimplementedRaftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftServer struct{}

func (UnimplementedRaftServer) Deliver(grpc.ClientStreamingServer[RaftMessage, DeliverAck]) error {
	return status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedRaftServer) mustEmbedUnimplementedRaftServer() {}
func (UnimplementedRaftServer) testEmbeddedByValue()              {}

// UnsafeRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftServer will
// result in compilation errors.
type UnsafeRaftServer interface {
	mustEmbedUnimplementedRaftServer()
}

func RegisterRaftServer(s grpc.ServiceRegistrar, srv RaftServer) {
	// If the following call panics, it indicates UnimplementedRaftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Raft_ServiceDesc, srv)
}

func _Raft_Deliver_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftServer).Deliver(&grpc.GenericServerStream[RaftMessage, DeliverAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Raft_DeliverServer = grpc.ClientStreamingServer[RaftMessage, DeliverAck]

// Raft_ServiceDesc is the grpc.ServiceDesc for Raft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Raft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.v1.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deliver",
			Handler:       _Raft_Deliver_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "raft.proto",
}
