// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: kv.proto

package kvpb

import (
	raftpb "github.com/sAchin-680/raftkv/proto/raftpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Consistency level requested for a read.
type ReadConsistency int32

const (
	ReadConsistency_READ_CONSISTENCY_UNSPECIFIED ReadConsistency = 0
	// Read-index: the leader confirms it is still the leader with a round of
	// heartbeats, waits for its state machine to catch up to the index that was
	// committed at that moment, and only then reads. Linearizable.
	ReadConsistency_READ_CONSISTENCY_LINEARIZABLE ReadConsistency = 1
	// Read straight out of the local state machine, no coordination. Fast, and
	// may return a value that is arbitrarily stale — a leader that has been
	// partitioned away but does not know it yet will happily serve from it.
	ReadConsistency_READ_CONSISTENCY_STALE ReadConsistency = 2
)

// Enum value maps for ReadConsistency.
var (
	ReadConsistency_name = map[int32]string{
		0: "READ_CONSISTENCY_UNSPECIFIED",
		1: "READ_CONSISTENCY_LINEARIZABLE",
		2: "READ_CONSISTENCY_STALE",
	}
	ReadConsistency_value = map[string]int32{
		"READ_CONSISTENCY_UNSPECIFIED":  0,
		"READ_CONSISTENCY_LINEARIZABLE": 1,
		"READ_CONSISTENCY_STALE":        2,
	}
)

func (x ReadConsistency) Enum() *ReadConsistency {
	p := new(ReadConsistency)
	*p = x
	return p
}

func (x ReadConsistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadConsistency) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (ReadConsistency) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x ReadConsistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadConsistency.Descriptor instead.
func (ReadConsistency) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

// Raft guarantees a command is applied at least once, not exactly once: a client
// whose request times out cannot tell whether the entry committed, so it retries,
// and the same command can end up in the log twice (§8 of the paper).
//
// Every write therefore carries a session. The state machine keeps the last
// sequence number and response it saw per client, and replays the stored response
// instead of re-applying a duplicate. Without this, a retried write is invisible
// to the KV map (Set is idempotent) but still corrupts the *history* a
// linearizability checker sees — which is exactly what Phase 3 is looking for.
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SequenceNum   uint64                 `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Session) GetSequenceNum() uint64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Consistency   ReadConsistency        `protobuf:"varint,2,opt,name=consistency,proto3,enum=kv.v1.ReadConsistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetConsistency() ReadConsistency {
	if x != nil {
		return x.Consistency
	}
	return ReadConsistency_READ_CONSISTENCY_UNSPECIFIED
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// The commit index this read was served at. Recorded in the operation history
	// so a failed linearizability check can be traced back to a specific point in
	// the log rather than just a wall-clock instant.
	ReadIndex     uint64 `protobuf:"varint,3,opt,name=read_index,json=readIndex,proto3" json:"read_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetReadIndex() uint64 {
	if x != nil {
		return x.ReadIndex
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

func (x *SetRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // log index at which the write committed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{6}
}

func (x *SetResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Existed       bool                   `protobuf:"varint,2,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

// Attached as a gRPC error detail when a request reaches a node that is not the
// leader, so a client can redirect in one hop instead of polling every peer.
// leader_hint is 0 when the node does not currently know of a leader.
type NotLeaderError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderHint    uint64                 `protobuf:"varint,1,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeaderError) Reset() {
	*x = NotLeaderError{}
	mi := &file_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeaderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeaderError) ProtoMessage() {}

func (x *NotLeaderError) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeaderError.ProtoReflect.Descriptor instead.
func (*NotLeaderError) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9}
}

func (x *NotLeaderError) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

func (x *NotLeaderError) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NodeId       uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State        string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "follower" | "candidate" | "leader"
	Term         uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId     uint64                 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex  uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	LastIndex    uint64                 `protobuf:"varint,7,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	Config       *raftpb.Configuration  `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	// Leader only: the last index each peer is known to have matched. The gap
	// between this and commit_index is replication lag, which is what the
	// dashboard and the quorum alert are built on.
	MatchIndex    map[uint64]uint64 `protobuf:"bytes,9,rep,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *StatusResponse) GetConfig() *raftpb.Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StatusResponse) GetMatchIndex() map[uint64]uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return nil
}

// Drives a joint-consensus membership change to completion: enter the joint
// configuration, wait for it to commit, then leave it for the target
// configuration. The call returns once the whole transition has committed.
type ChangeMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voters        []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	Learners      []uint64               `protobuf:"varint,2,rep,packed,name=learners,proto3" json:"learners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMembershipRequest) Reset() {
	*x = ChangeMembershipRequest{}
	mi := &file_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMembershipRequest) ProtoMessage() {}

func (x *ChangeMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMembershipRequest.ProtoReflect.Descriptor instead.
func (*ChangeMembershipRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeMembershipRequest) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *ChangeMembershipRequest) GetLearners() []uint64 {
	if x != nil {
		return x.Learners
	}
	return nil
}

type ChangeMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *raftpb.Configuration  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMembershipResponse) Reset() {
	*x = ChangeMembershipResponse{}
	mi := &file_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMembershipResponse) ProtoMessage() {}

func (x *ChangeMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMembershipResponse.ProtoReflect.Descriptor instead.
func (*ChangeMembershipResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeMembershipResponse) GetConfig() *raftpb.Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ChangeMembershipResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\x05kv.v1\x1a\n" +
	"raft.proto\"I\n" +
	"\aSession\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x04R\vsequenceNum\"\x11\n" +
	"\x0fRegisterRequest\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\"X\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x128\n" +
	"\vconsistency\x18\x02 \x01(\x0e2\x16.kv.v1.ReadConsistencyR\vconsistency\"X\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"read_index\x18\x03 \x01(\x04R\treadIndex\"^\n" +
	"\n" +
	"SetRequest\x12(\n" +
	"\asession\x18\x01 \x01(\v2\x0e.kv.v1.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"#\n" +
	"\vSetResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\"K\n" +
	"\rDeleteRequest\x12(\n" +
	"\asession\x18\x01 \x01(\v2\x0e.kv.v1.SessionR\asession\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"@\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x18\n" +
	"\aexisted\x18\x02 \x01(\bR\aexisted\"X\n" +
	"\x0eNotLeaderError\x12\x1f\n" +
	"\vleader_hint\x18\x01 \x01(\x04R\n" +
	"leaderHint\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"\x0f\n" +
	"\rStatusRequest\"\x8e\x03\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderId\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12\x1d\n" +
	"\n" +
	"last_index\x18\a \x01(\x04R\tlastIndex\x12.\n" +
	"\x06config\x18\b \x01(\v2\x16.raft.v1.ConfigurationR\x06config\x12F\n" +
	"\vmatch_index\x18\t \x03(\v2%.kv.v1.StatusResponse.MatchIndexEntryR\n" +
	"matchIndex\x1a=\n" +
	"\x0fMatchIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"M\n" +
	"\x17ChangeMembershipRequest\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1a\n" +
	"\blearners\x18\x02 \x03(\x04R\blearners\"`\n" +
	"\x18ChangeMembershipResponse\x12.\n" +
	"\x06config\x18\x01 \x01(\v2\x16.raft.v1.ConfigurationR\x06config\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index*r\n" +
	"\x0fReadConsistency\x12 \n" +
	"\x1cREAD_CONSISTENCY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dREAD_CONSISTENCY_LINEARIZABLE\x10\x01\x12\x1a\n" +
	"\x16READ_CONSISTENCY_STALE\x10\x022\xd4\x01\n" +
	"\x02KV\x12;\n" +
	"\bRegister\x12\x16.kv.v1.RegisterRequest\x1a\x17.kv.v1.RegisterResponse\x12,\n" +
	"\x03Get\x12\x11.kv.v1.GetRequest\x1a\x12.kv.v1.GetResponse\x12,\n" +
	"\x03Set\x12\x11.kv.v1.SetRequest\x1a\x12.kv.v1.SetResponse\x125\n" +
	"\x06Delete\x12\x14.kv.v1.DeleteRequest\x1a\x15.kv.v1.DeleteResponse2\x95\x01\n" +
	"\aCluster\x125\n" +
	"\x06Status\x12\x14.kv.v1.StatusRequest\x1a\x15.kv.v1.StatusResponse\x12S\n" +
	"\x10ChangeMembership\x12\x1e.kv.v1.ChangeMembershipRequest\x1a\x1f.kv.v1.ChangeMembershipResponseB.Z,github.com/sAchin-680/raftkv/proto/kvpb;kvpbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kv_proto_goTypes = []any{
	(ReadConsistency)(0),             // 0: kv.v1.ReadConsistency
	(*Session)(nil),                  // 1: kv.v1.Session
	(*RegisterRequest)(nil),          // 2: kv.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 3: kv.v1.RegisterResponse
	(*GetRequest)(nil),               // 4: kv.v1.GetRequest
	(*GetResponse)(nil),              // 5: kv.v1.GetResponse
	(*SetRequest)(nil),               // 6: kv.v1.SetRequest
	(*SetResponse)(nil),              // 7: kv.v1.SetResponse
	(*DeleteRequest)(nil),            // 8: kv.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 9: kv.v1.DeleteResponse
	(*NotLeaderError)(nil),           // 10: kv.v1.NotLeaderError
	(*StatusRequest)(nil),            // 11: kv.v1.StatusRequest
	(*StatusResponse)(nil),           // 12: kv.v1.StatusResponse
	(*ChangeMembershipRequest)(nil),  // 13: kv.v1.ChangeMembershipRequest
	(*ChangeMembershipResponse)(nil), // 14: kv.v1.ChangeMembershipResponse
	nil,                              // 15: kv.v1.StatusResponse.MatchIndexEntry
	(*raftpb.Configuration)(nil),     // 16: raft.v1.Configuration
}
var file_kv_proto_depIdxs = []int32{
	0,  // 0: kv.v1.GetRequest.consistency:type_name -> kv.v1.ReadConsistency
	1,  // 1: kv.v1.SetRequest.session:type_name -> kv.v1.Session
	1,  // 2: kv.v1.DeleteRequest.session:type_name -> kv.v1.Session
	16, // 3: kv.v1.StatusResponse.config:type_name -> raft.v1.Configuration
	15, // 4: kv.v1.StatusResponse.match_index:type_name -> kv.v1.StatusResponse.MatchIndexEntry
	16, // 5: kv.v1.ChangeMembershipResponse.config:type_name -> raft.v1.Configuration
	2,  // 6: kv.v1.KV.Register:input_type -> kv.v1.RegisterRequest
	4,  // 7: kv.v1.KV.Get:input_type -> kv.v1.GetRequest
	6,  // 8: kv.v1.KV.Set:input_type -> kv.v1.SetRequest
	8,  // 9: kv.v1.KV.Delete:input_type -> kv.v1.DeleteRequest
	11, // 10: kv.v1.Cluster.Status:input_type -> kv.v1.StatusRequest
	13, // 11: kv.v1.Cluster.ChangeMembership:input_type -> kv.v1.ChangeMembershipRequest
	3,  // 12: kv.v1.KV.Register:output_type -> kv.v1.RegisterResponse
	5,  // 13: kv.v1.KV.Get:output_type -> kv.v1.GetResponse
	7,  // 14: kv.v1.KV.Set:output_type -> kv.v1.SetResponse
	9,  // 15: kv.v1.KV.Delete:output_type -> kv.v1.DeleteResponse
	12, // 16: kv.v1.Cluster.Status:output_type -> kv.v1.StatusResponse
	14, // 17: kv.v1.Cluster.ChangeMembership:output_type -> kv.v1.ChangeMembershipResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
